// Colors
export const colorHighlight: string = "#cdddf6"
export const colorWarn: string = "#ffe208"
export const colorHighlightBright: string = "#f4f8ff"
export const colorWarnBright: string = "#fff07f"
export const colorBackground: string = "#303136"
export const colorGray: string = "#6a6a72"
export const colorGrayDark: string = "#424147"
export const colorNeutralGreen: string = "#79e99e"
export const colorReverseOrange:string = "#dea767"